sonar.projectKey=EventSCI
sonar.projectName=EventSCI
sonar.sources=lib
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/*.mocks.dart,**/generated/**